spring:
  main:
    banner-mode: off
    log-startup-info: false
  application:
    name: rina-irsync
  threads:
    virtual:
      enabled: true
  shell:
    interactive:
      enabled: true
    history:
      enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} : %m%n"