spring:
  main:
    banner-mode: off
  application:
    name: rina-irsync
  threads:
    virtual:
      enabled: true

  shell:
    interactive:
      enabled: true
    history:
      enabled: false

#logging:
#  level:
#    root: OFF
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} : %m%n"