spring:
  main:
    banner-mode: off
    log-startup-info: false
    web-application-type: NONE
  application:
    name: rina-irsync
  threads:
    virtual:
      enabled: true
  shell:
    interactive:
      enabled: true
    history:
      enabled: false

logging:
  level:
    org.jline: OFF          # Completely disable JLine logs
    org.springframework.shell: INFO  # Keep Spring Shell logs visible
    org.springframework.boot.SpringApplication: ERROR
    org.springframework.boot.context.config: ERROR
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} : %m%n"